version: '3.4'
networks:
  production:

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5136:80"
    networks:
      - production

  client:
    build: "Client/"
    ports:
      - "80:80"
    networks:
      - production
