version: '3.4'
networks:
  production:

services:
  api:
    env_file: api-environment.env
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5136:80"
    networks:
      - production

  client:
    build: "Client/"
    ports:
      - "80:80"
    networks:
      - production
    # For faster testing angular builds.
    volumes:
      - type: bind
        source: Client/dist/client
        target: /usr/share/nginx/html
    depends_on: 
    - api

  db:
    container_name: "DndItem"
    env_file: db-environment.env
    ports:
    -  1401:1433 
    image: mcr.microsoft.com/mssql/server
    restart: on-failure
    networks:
      - production
    volumes:
      -  sql-item-manage:/var/opt/mssql 

volumes:
  sql-item-manage:
