CREATE DATABASE Administration
GO
USE Administration
GO
CREATE TABLE DMs (
  DmID INT PRIMARY KEY IDENTITY,
  DmLogin VARCHAR(20) UNIQUE NOT NULL,
  DmPassword VARCHAR(65) NOT NULL
)
CREATE TABLE Rooms (
  RoomID INT PRIMARY KEY IDENTITY,
  RoomName VARCHAR(20) NOT NULL,
  RoomPassword VARCHAR(65) NOT NULL,
  Started BIT NOT NULL DEFAULT(0),
  DmId INT FOREIGN KEY REFERENCES DMs(DmID) ON DELETE CASCADE NOT NULL 
)
GO