CREATE DATABASE ItemManagement
GO
USE ItemManagement
GO
CREATE TABLE ItemCategories(
  CategoryID INT PRIMARY KEY IDENTITY,
  CategoryName VARCHAR(150) UNIQUE NOT NULL
)
CREATE TABLE Actions (
  ActionID INT PRIMARY KEY IDENTITY,
  Act VARCHAR(50) NOT NULL UNIQUE
)
CREATE TABLE Characters (
  CharacterID INT PRIMARY KEY IDENTITY,
  CharacterName VARCHAR(30) NOT NULL,
  Currency INT NOT NULL DEFAULT(0),
  RoomId INT
)
CREATE TABLE Items (
  ItemID INT PRIMARY KEY IDENTITY,
  ItemName NVARCHAR(50) NOT NULL,
  ItemMaxDurability INT NOT NULL DEFAULT(1),
  Price INT NOT NULL DEFAULT(0),
  Weight REAL NOT NULL DEFAULT(0),
  ItemCategoryId INT FOREIGN KEY REFERENCES ItemCategories(CategoryID) NOT NULL,
  SecretItemDescription VARCHAR(1000) NULL,
  ItemDescription NVARCHAR(1500) NULL,
  RoomId INT NULL
)
CREATE TABLE ItemsActions (
  ItemID INT FOREIGN KEY REFERENCES Items(ItemID),
  ActionID INT FOREIGN KEY REFERENCES Actions(ActionID),
  PRIMARY KEY (ItemID, ActionID)
)
CREATE TABLE CharactersItems (
  ItemID INT FOREIGN KEY REFERENCES Items(ItemID),
  CharacterID INT FOREIGN KEY REFERENCES Characters(CharacterID) ON DELETE CASCADE,
  ItemNumber INT NOT NULL DEFAULT(0),
  CurrentDurability REAL NOT NULL DEFAULT(1),
  PRIMARY KEY (ItemID, CharacterID)
)
GO
INSERT INTO ItemCategories(CategoryName)
VALUES
  ('ARMOR'),
  ('POTION'),
  ('RING'),
  ('ROD'),
  ('SCROLL'),
  ('STAFF'),
  ('WAND'),
  ('WEAPON'),
  ('WONDROUS'),
  ('OTHER GEAR')
GO
