CREATE DATABASE ItemManagement
GO
USE ItemManagement
GO
CREATE TABLE ItemCategories(
  CategoryID INT PRIMARY KEY IDENTITY,
  CategoryName VARCHAR(150) UNIQUE NOT NULL
)
CREATE TABLE DMs (
  DmID INT PRIMARY KEY IDENTITY,
  DmLogin VARCHAR(20) UNIQUE NOT NULL,
  DmPassword VARCHAR(25) NOT NULL CHECK(Len(DmPassword) > 4)
)
CREATE TABLE Actions (
  ActionID INT PRIMARY KEY IDENTITY,
  Act VARCHAR(50) NOT NULL UNIQUE
)
CREATE TABLE Rooms (
  RoomID INT PRIMARY KEY IDENTITY,
  RoomName VARCHAR(20) NOT NULL,
  RoomPassword VARCHAR(25) NOT NULL CHECK(Len(RoomPassword) > 4),
  Started BIT NOT NULL DEFAULT(0),
  Dm INT FOREIGN KEY REFERENCES DMs(DmID) ON DELETE CASCADE NOT NULL 
)
GO
CREATE TABLE Characters (
  CharacterID INT PRIMARY KEY IDENTITY,
  CharacterName VARCHAR(30) NOT NULL,
  Currency INT NOT NULL DEFAULT(0),
  Room INT FOREIGN KEY REFERENCES Rooms(RoomID) ON DELETE CASCADE
)
CREATE TABLE Items (
  ItemID INT PRIMARY KEY IDENTITY,
  ItemName NVARCHAR(50) NOT NULL,
  ItemMaxDurability INT NOT NULL DEFAULT(1),
  Price INT NOT NULL DEFAULT(0),
  Weight REAL NOT NULL DEFAULT(0),
  ItemCategory INT FOREIGN KEY REFERENCES ItemCategories(CategoryID) NOT NULL,
  SecretItemDescription VARCHAR(1000) NULL,
  ItemDescription NVARCHAR(1500) NULL,
  Room INT FOREIGN KEY REFERENCES Rooms(RoomID) NULL
)
GO
CREATE TABLE ItemsActions (
  ItemID INT FOREIGN KEY REFERENCES Items(ItemID),
  ActionID INT FOREIGN KEY REFERENCES Actions(ActionID),
  PRIMARY KEY (ItemID, ActionID)
)
CREATE TABLE CharactersItems (
  ItemID INT FOREIGN KEY REFERENCES Items(ItemID),
  CharacterID INT FOREIGN KEY REFERENCES Characters(CharacterID) ON DELETE CASCADE,
  ItemNumber INT NOT NULL DEFAULT(0),
  CurrentDurability REAL NOT NULL DEFAULT(1),
  PRIMARY KEY (ItemID, CharacterID)
)
GO
INSERT INTO ItemCategories(CategoryName)
VALUES
  ('ARMOR'),
  ('POTION'),
  ('RING'),
  ('ROD'),
  ('SCROLL'),
  ('STAFF'),
  ('WAND'),
  ('WEAPON'),
  ('WONDROUS'),
  ('OTHER GEAR')
GO
